### ISSUE TITLE
USDC Transactions

### ISSUE THREAD

**Issue by kalimuscle** [bitaccess/coinlib#212]
have thought to implement USDC token?

**Comment by dylanseago** [comment]
USDC ERC20 token is supported in the ethereum-payments package
See: https://github.com/go-faast/coin-payments/tree/master/packages/ethereum-payments/src/erc20

**Comment by kalimuscle** [comment]
thanks

**Comment by kalimuscle** [comment]
Oh I am newbie in crypto world, I am trying to test erc20 (USDC). I have been testing the Ropsten testnet with USDC. I have received the tokens but I have not been able to create a transaction. Please have some example code with ERC20

**Comment by dylanseago** [comment]
When creating the payments instance you need to provide extra fields to tell it what token to use. It would look something like this:

```typescript
const usdcPayments = new HdErc20Payments({
    hdKey: 'xprv....',
    networkType: 'testnet',
    fullNode: 'ropsten.infura.io/v3/yourkeyhere',
    symbol: 'USDC',
    name: 'USD Coin',
    decimals: 6,
    tokenAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
})

const senderIndex = 0
const { address: senderAddress } = await usdcPayments.getPayport(senderIndex)
const unsignedTx = await usdcPayments.createTransaction(senderIndex, '0xrecipient', 1234)
const signedTx = await usdcPayments.signTransaction(unsignedTx)
const { id: txHash } = await usdcPayments.broadcastTransaction(signedTx)
```

**Comment by kalimuscle** [comment]
Thanks a lot. Thank you for helping this humble beginner of the crypto world

**Comment by kalimuscle** [comment]
Hi again, I'm getting this error:

Error: Cannot derive payport 1 - masterAddress is falsy

Do you know what's happening? What is the function of masterAddress?

Thanks again

**Comment by dylanseago** [comment]
@kalimuscle Great question. The erc20 payments work slightly different from the ethereum/bitcoin implementations. Typically getPayport will just derive an address at the index you ask for based on the bip32/44 standard. However a plain ethereum address is not particularly useful for receiving incoming token deposits because that address wouldn't have any ETH to move the funds out. This library was designed with enterprises in mind so being able to generate a unique address that could be given to a customer and swept in one step without needing to top it up with ether was crucial.

The solution to this was to implement a token deposit smart contract that must be deployed in advance by the address at payport 0. The smart contract allows you to generate unique ethereum addresses using the create2 feature of the EVM. When you send or sweep tokens from this address the smart contract deploys an temporary minimal proxy contract of itself, sends the tokens to the recipient, and self destructs itself to get the gas refund. So effectively it facilitates erc20 token transfers while only needing to maintain a balance in a single owner address (payport #0). It's quite gas efficient too, the overhead is only around 20-30k on top of a typical erc20 transfer. Which is much cheaper than the alternatives.

This contract can be deployed using the `createServiceTransaction` method to deploy the contract. Then you'd set that contract address as the `masterAddress` in the payments config.

For example:
```typescript
const baseConfig = {
    hdKey: 'xprv....',
    networkType: 'testnet',
    fullNode: 'ropsten.infura.io/v3/yourkeyhere',
}

/*
 * One time deployment of smart contract necessary to facilitate receiving future erc20 deposits
 */
const ethPayments = new HdEthereumPayments(baseConfig)
const { address: primaryAddress } = await ethPayments.getPayport(0)
// Add some ether to primaryAddress to facilitate contract deployment. It controls the master contract and pays fees for all erc20 transfers out of payports at index >=1
const deployMasterUnsignedTx = await ethPayments.createServiceTransaction()
const deployMasterSignedTx = await ethPayments.signTransaction(deployMasterUnsignedTx)
const { id: deployMasterTxHash } = await ethPayments.broadcastTransaction(deployMasterSignedTx)
// You'll want to regularly look up the hash until it confirms
const deployTxInfo = await ethPayments.getTransactionInfo(deployMasterTxHash)
if (deployTxInfo.confirmations > 10) {
  // master contract deployment confirmed
  const { contractAddress: masterAddress } = txInfo.data
  // Save this master address to use for erc20 payments config. It can be used for all tokens, so you only need to do this once per primary address
}

/*
 * Sweep the tokens from deposit address (payport #1) to recipient address 0xrecipient.
 * You **don't** need to have an ether balance at the deposit address, only your primary address (payport #0)
 */
const usdcPayments = new HdErc20Payments({
    ...baseConfig,
    masterAddress, // from earlier deployment
    symbol: 'USDC',
    name: 'USD Coin',
    decimals: 6,
    tokenAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
})

const depositIndex = 1
const { address: depositAddress } = await usdcPayments.getPayport(depositIndex)
const unsignedTx = await usdcPayments.createSweepTransaction(depositIndex, '0xrecipient')
const signedTx = await usdcPayments.signTransaction(unsignedTx)
const { id: txHash } = await usdcPayments.broadcastTransaction(signedTx)
// On etherscan you'll see the transaction "from" your primaryAddress and "to" your masterAddress
// The result will be moving all tokens from depositAddress to 0xrecipient
```

**Comment by kalimuscle** [comment]
Hello again,

Great explanation, now I understand better. When I checked the code with the tests, some doubts jumped.

There was a moment that I imagined that masterAddress was used in something like what you are telling me.

Following my instincts, I tried to implement something. I managed to obtain the balance of USDC from an address to which I sent test tokens, but when I tried to create a transaction I always had problems with the transaction gas

**Comment by kalimuscle** [comment]
Can I deploy the contract only once and use the masterAddress for all tokens or do I need to deploy the contract every time I need to do a transaction instead?

**Comment by kalimuscle** [comment]
Is it not necessary to define at some point the ABI of the USDC token?

**Comment by kalimuscle** [comment]
I'm getting a invalid sender exception from broadcastTransation

**Comment by dylanseago** [comment]
> Can I deploy the contract only once and use the masterAddress for all tokens or do I need to deploy the contract every time I need to do a transaction instead?

Only once per primary address. The same contract works for all tokens. The ABI is already built into this library.

I can't do much to help you without your code

**Comment by kalimuscle** [comment]
> > Can I deploy the contract only once and use the masterAddress for all tokens or do I need to deploy the contract every time I need to do a transaction instead?
> 
> Only once per primary address. The same contract works for all tokens. The ABI is already built into this library.
> 
> I can't do much to help you without your code

Ok, this the code

try {
    const baseConfig = {
      hdKey:
        "xprv...",
      networkType: NetworkType.Testnet,
      gasStation: GAS_STATION_URL,
      fullNode: ROPSTEN_NETWORK_URL
    };

    /*
     * One time deployment of smart contract necessary to facilitate receiving future erc20 deposits
     */
    const ethPayments = new HdEthereumPayments(baseConfig);
    const { address: primaryAddress } = await ethPayments.getPayport(0);

    // Add some ether to primaryAddress to facilitate contract deployment. It controls the master contract and pays fees for all erc20 transfers out of payports at index >=1
    const deployMasterUnsignedTx = await ethPayments.createServiceTransaction(
      undefined,
      { gas: "4700000" }
    );
    const deployMasterSignedTx = await ethPayments.signTransaction(
      deployMasterUnsignedTx
    );
    const { id: deployMasterTxHash } = await ethPayments.broadcastTransaction(
      deployMasterSignedTx
    );
    // You'll want to regularly look up the hash until it confirms
    const deployTxInfo = await ethPayments.getTransactionInfo(
      deployMasterTxHash
    );
    if (deployTxInfo.confirmations > 10) {
      // master contract deployment confirmed
      const { contractAddress: masterAddress } = txInfo.data;
      // Save this master address to use for erc20 payments config. It can be used for all tokens, so you only need to do this once per primary address
    }

    const usdcPayments = new HdErc20Payments({
      ...baseConfig,
      masterAddress, // from earlier deployment
      symbol: "USDC",
      name: "USD Coin",
      decimals: 6,
      tokenAddress: USDC_CONTRACT_ADDRESS
    });

    const depositIndex = 1;
    const { address: depositAddress } = await usdcPayments.getPayport(
      depositIndex
    );
    const unsignedTx = await usdcPayments.createSweepTransaction(
      depositIndex,
      "0x9fFfB5002A7CE674766661a1731757D04D1100E6"
    );
    const signedTx = await usdcPayments.signTransaction(unsignedTx);
    const { id: txHash } = await usdcPayments.broadcastTransaction(signedTx);
    
  } catch (error) {
    console.log(error);
  }



it's the same code except the arguments in createServiceTransaction

**Comment by dylanseago** [comment]
@kalimuscle The code I provided wasn't complete. You'll still need to add a loop around the getTransactionInfo until it's actually confirmed then you can use the master address from it

**Comment by kalimuscle** [comment]
Hi I add a loop using setInterval for check getTransactionInfo

const main = async () => {
  try {
    const baseConfig = {
      hdKey:
        "xprv....",
      networkType: NetworkType.Testnet,
      //gasStation: GAS_STATION_URL,
      fullNode: LOCAL_NETWORK_URL,
      tokenAddress: "",
      masterAddress: "",
      depositKeyIndex: 0
    };

    /*
     * One time deployment of smart contract necessary to facilitate receiving future erc20 deposits
     */
    const ethPayments = new HdEthereumPayments(baseConfig);
    const { address } = await ethPayments.getPayport(0);

    // Add some ether to primaryAddress to facilitate contract deployment. It controls the master contract and pays fees for all erc20 transfers out of payports at index >=1
    const deployMasterUnsignedTx = await ethPayments.createServiceTransaction(
      undefined,
      {
        gas: "4700000"
      }
    );
    const deployMasterSignedTx = await ethPayments.signTransaction(
      deployMasterUnsignedTx
    );
    const { id } = await ethPayments.broadcastTransaction(deployMasterSignedTx);
    console.log("id hash from broadcast:", id);

    loop(ethPayments, id);
    //while (true) {}
  } catch (error) {
    console.log(error);
  }
};

const loop = async (ethPayments, deployMasterTxHash) => {
  console.log("inside loop");

  const functionInterval = setInterval(async () => {
    let contractAddress;

    console.log("Verifying transaction ...");
    // You'll want to regularly look up the hash until it confirms
    const deployTxInfo = await ethPayments.getTransactionInfo(
      deployMasterTxHash
    );

    if (deployTxInfo.isConfirmed) {
      console.log("Transaction is confirmed");
      // master contract deployment confirmed
      contractAddress = deployTxInfo.data.contractAddress;
      console.log("contract address:", contractAddress);

      // Save this master address to use for erc20 payments config. It can be used for all tokens, so you only need to do this once per primary address
      const usdcPayments = new HdErc20Payments({
        ...baseConfig,
        masterAddress: contractAddress, // from earlier deployment
        symbol: "USDC",
        name: "USD Coin",
        decimals: 6,
        tokenAddress: USDC_CONTRACT_ADDRESS
      });

      const depositIndex = 1;
      const { address } = await usdcPayments.getPayport(depositIndex);

      console.log(address);
      const unsignedTx = await usdcPayments.createSweepTransaction(
        "0xD4E45ae7DC0701f411410187b1E0269D61d4cF27",
        "0xdd7069791FAd5c380338352E47468C194cba5651"
      );
      const signedTx = await usdcPayments.signTransaction(unsignedTx);
      const { id } = await usdcPayments.broadcastTransaction(signedTx);
      // On etherscan you'll see the transaction "from" your primaryAddress and "to" your masterAddress
      // The result will be moving all tokens from depositAddress to 0xrecipient

      clearInterval(functionInterval);
    } else {
      console.log("Transaction not confirmed");
    }
  }, 5000);
};

main();

**Comment by kalimuscle** [comment]
Other observation, in this code I am using ganache-cli, broadcastTrnasaction work and I can check the transaction. However, if I use ropsten network I am getting "invalid sender" exception from broadcast transaction

**Comment by dzdidi** [comment]
@kalimuscle  it might be caused  by the token address as this is network specific:
* tokenAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48' - is for mainnet
* tokenAddress: '0x07865c6e87b9f70255377e024ace6630c1eaa37f' - is for ropsten

ref https://developers.circle.com/docs/usdc-on-testnet

**Comment by kalimuscle** [comment]
Hi @dzdidi , tokenAddress is fine, the problem occurs when I run the broadcastTransaction at the beginning

**Comment by dzdidi** [comment]
@kalimuscle 
sorry but it is hard to say what exactly is happening without any concrete information about setup, invocation, execution. Output and or exact steps to recreate.

The only help I can do is to refer you to this [test](https://github.com/bitaccess/coinlib/blob/master/packages/ethereum-payments/test/erc20/end-to-end.test.ts#L82) which uses local instance of [ganache-code](https://github.com/trufflesuite/ganache-core)
 there you can adjust test parameters to your preferences.

**Comment by Badameron31** [comment]
> @badameron@coinomi.com

**Comment by kalimuscle** [comment]
This is the exception :

[ethereum-payments] Ethereum broadcast tx unsuccessful 0x4316e1718f52c6792323b19329ac5055df04346dd55b7955946a7165aae63438: Returned error: invalid sender
Error: Ethereum broadcast tx unsuccessful: 0x4316e1718f52c6792323b19329ac5055df04346dd55b7955946a7165aae63438 Returned error: invalid sender

**Comment by kalimuscle** [comment]
Searching in Internet I found that this error can be with chainId

**Comment by kalimuscle** [comment]
Hi guys, I solved the problem in Ropsten, in the config I am using networkType: NetworkType.Testnet instead of
  network: "testnet".

Thanks for your help

**Comment by dylanseago** [comment]
@kalimuscle Ah, yes sorry my example config was incorrect. Glad you were able to figure it out
